### PR TITLE
Publish Microsoft Authored templates to azure samples browser 

### PR DESCRIPTION
**Pull request by v-xuto**
Update metadata, and publish `APICenter-Portal-Starter` template to azure samples browser.

@hemarina and @justinyoo for notification.

### CODE REVIEW

**Comment by justinyoo** [comment]
@pierceboggan @juliajuju93 Please review and merge

**Comment by justinyoo** [comment]
@v-xuto Can we avoid this frontmatter? Wonder if there's an alternative way adding this metadata.

**Comment by v-xuto** [comment]
@hemarina Can we create a new `docs/README.md` file in this repo and add metadata to the `README.md` under docs, such as: 
https://github.com/azure-samples/azure-search-openai-javascript/tree/main/docs.

**Comment by v-xuto** [comment]
@justinyoo We created a subfolder `docs/README.md` to add metadata. Do you think this is okay

**Comment by justinyoo** [comment]
@pierceboggan Here's the new suggestion. How does this look to you?

**Comment by v-xuto** [comment]
@pierceboggan Could you help review this PR. Thanks a lot.

**Review by Bruce-Moe — COMMENTED** [review]
I changed the main README.md file recently, could you please take a look and see if those changes should be in `docs/README.md` as well? See https://github.com/Azure/APICenter-Portal-Starter/commit/cc88e5aa6a43592feb410c39abaab54959c02e97

**Comment by Bruce-Moe** [comment]
I reviewed the PR and left a comment, thanks.

**Comment by v-xuto** [comment]
> I changed the main README.md file recently, could you please take a look and see if those changes should be in `docs/README.md` as well? See [cc88e5a](https://github.com/Azure/APICenter-Portal-Starter/commit/cc88e5aa6a43592feb410c39abaab54959c02e97)
> 
> @hemarina @v-xuto

@Bruce-Moe I have updated `doc/READmE.md` based on main README.md file. Please review.

**Review by Bruce-Moe — APPROVED** [review]

**Comment by v-xuto** [comment]
@Bruce-Moe Could you help merge this PR? Thanks a lot.

**Pull request merged**
